##NUMPY



In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#python list vs numpy array
numbers = [1,2,3]

print(type(numbers))

<class 'list'>


In [ ]:
numbers=np.array([1,2,3])

print(type(numbers)) #ndarray =   N-dimensional array

<class 'numpy.ndarray'>


In [7]:
#2d array
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [8]:
#zeroes

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
arr = np.array([1,2,3])

print(arr.dtype)

int64


In [17]:
arr = np.array([1,2,3],dtype=float)
print(arr)

[1. 2. 3.]


In [20]:
#shape
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [21]:
print(matrix.ndim)

2


In [22]:
matrix.size

6

In [24]:
#indexing

arr = np.array([10,20,30,40,50])
print(arr[0])

10


In [25]:
print(arr[-1])

50


In [ ]:
#2d indexing
matrix = np.array([[1,2,3],[4,5,6]])

print(matrix[1][2]) #here 1 indicates second row and 2 indicates 2nd row 3rd column

6


In [27]:
#slicing
arr = np.array([10,20,30,40,50])
arr[:3]

array([10, 20, 30])

In [28]:
arr[-2:]

array([40, 50])

In [29]:
arr[1:4]

array([20, 30, 40])

In [32]:
#mathematical operations
arr=np.array([1,2,3])
arr+=5
print(arr)

[6 7 8]


In [33]:
arr*=10
print(arr)

[60 70 80]


In [35]:
arr**=2
print(arr)

[12960000 24010000 40960000]


In [37]:
arr=arr/2
print(arr)

[ 6480000. 12005000. 20480000.]


In [38]:
#array operations

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [39]:
print(a*b)

[ 4 10 18]


In [40]:
#broadcasting
arr = np.array([10,20,30])
print(arr + 10)

[20 30 40]


In [41]:
prices = np.array([100,200,300])
discount = 0.9

print(prices * discount)

[ 90. 180. 270.]
