Exercise 1

Create

[5,10,15,20,25]

using NumPy.

In [3]:
import numpy as np
arr = np.array([5,10,15,20,25])

print(arr)

[ 5 10 15 20 25]


Exercise 1

Create

[5,10,15,20,25]

using NumPy.

In [8]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Exercise 3

Create numbers from 100 to 200 with step 10.

In [11]:
arr = np.arange(100,200,10)
print(arr)

[100 110 120 130 140 150 160 170 180 190]


Exercise 4

Find the shape of

[[1,2],
 [3,4],
 [5,6]]

In [12]:
arr = np.array([[1,2],
 [3,4],
 [5,6]])

print(arr.shape)

(3, 2)


Exercise 5

Extract

30 40 50

from

[10,20,30,40,50,60]

In [13]:
arr = np.array([10,20,30,40,50,60])

print(arr[2:5])

[30 40 50]


Exercise 6

Multiply every element by 100.

In [14]:
arr = arr*100
print(arr)

[1000 2000 3000 4000 5000 6000]


Exercise 7

Add two arrays

[1,2,3]

[10,20,30]

In [16]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a+b)

[11 22 33]


Exercise 8

Create a 3×3 matrix filled with 9.

In [18]:
arr = np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
